# Generated by Django 2.2.28 on 2024-04-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='img',
            new_name='image',
        ),
    ]
