# Generated by Django 2.2.28 on 2024-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default="2024-04-23"),
            preserve_default=False,
        ),
    ]
